<a href="https://colab.research.google.com/github/saeloman/APNEE_SOMMEIL/blob/main/ForwardPropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
np.random.seed(42)
num_samples = 20

In [ ]:
age = np.random.randint(18, 90, size= num_samples)
age

array([69, 32, 89, 78, 38, 41, 20, 39, 70, 19, 47, 55, 19, 81, 77, 38, 50,
       75, 39, 66])

In [ ]:
income = np.random.randint (20000, 100000, size = num_samples)
loan_amount = np.random.randint(5000, 100000, size = num_samples)
num_accounts = np.random.randint(1, 10, size = num_samples)

#creation des caracteristque d'entreee

In [ ]:
X = np.column_stack((age, income, loan_amount, num_accounts))
X

array([[   69, 45658, 73148,     2],
       [   32, 38431, 28483,     4],
       [   89, 22747, 53555,     8],
       [   78, 79150, 22159,     7],
       [   38, 85725, 85077,     9],
       [   41, 55773, 40920,     8],
       [   20, 87435, 97067,     5],
       [   39, 76886, 72121,     2],
       [   70, 86803, 74479,     5],
       [   19, 51551, 94475,     8],
       [   47, 31394, 24457,     9],
       [   55, 89092, 71557,     9],
       [   19, 23890, 82189,     1],
       [   81, 61606, 83953,     9],
       [   77, 30627, 57995,     7],
       [   38, 28792, 45757,     9],
       [   50, 93969, 14692,     8],
       [   75, 63001, 50758,     1],
       [   39, 96552, 77409,     8],
       [   66, 43897, 76211,     8]])

les Mathematiques

Couche Cachénp
 1. Calcule de l entre de la couche cachénp.
 Z1 = W1.X+b1

In [ ]:
#fonction d'activation ReLu
def relu(X):
  return np.maximum(0,X)


In [ ]:
#Fonction d'actiavtion Sigmoid
def sigmoid(x):
  return 1/(1+np.exp(-X))

In [ ]:
# Nombre de neurone
#hidden_size = 5
#input_size = X. shape [0]
#np.random.seed (42)
#W1= np.random.rand(hidden_size, input_size)
#W1




# Nombre de neurone
hidden_size = 5
input_size = X. shape [0]
output_size = 1
np.random.seed (42)
W1 = np.random.rand(hidden_size, input_size)
b1 = np.random.rand(hidden_size, 1)
w2 = np.random.rand(output_size, hidden_size)
b2 = np.random.rand(output_size, 1)

In [ ]:
b1= np.random.rand(hidden_size, 1)
b1

array([[0.16122129],
       [0.92969765],
       [0.80812038],
       [0.63340376],
       [0.87146059]])

In [ ]:
output_size = 1
W2= np.random.rand(output_size, input_size)
W2

array([[0.80367208, 0.18657006, 0.892559  , 0.53934224, 0.80744016,
        0.8960913 , 0.31800347, 0.11005192, 0.22793516, 0.42710779,
        0.81801477, 0.86073058, 0.00695213, 0.5107473 , 0.417411  ,
        0.22210781, 0.11986537, 0.33761517, 0.9429097 , 0.32320293]])

In [ ]:
b2= np.random.rand(output_size, 1)
b2

array([[0.51879062]])

In [ ]:
#Forward pass
z1 = np.dot (W1, X) + b1
a1 = relu(z1)
a1

array([[4.70002734e+02, 5.47117029e+05, 5.68199010e+05, 5.14302164e+01],
       [5.17504678e+02, 5.29932449e+05, 5.49408300e+05, 6.45319295e+01],
       [5.06320674e+02, 5.41952222e+05, 5.68016191e+05, 6.51594860e+01],
       [4.89976156e+02, 5.12752789e+05, 5.32920683e+05, 6.67014416e+01],
       [4.99673163e+02, 5.76012136e+05, 6.37765115e+05, 5.55448389e+01]])

In [ ]:
#z2 = np.dot(W2, a1.T) + b2
z2 = np.dot (W2, a1) + b2
a2 = sigmoid(z2)
a2

array([[0.81246225, 0.4662743 , 0.13948675, 0.97797977]])

In [ ]:
import numpy as np

# Définition de la fonction sigmoid
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Initialisation des matrices et vecteurs avec des dimensions compatibles
W2 = np.random.randn(1, 5)  # Poids de la couche (1 neurone de sortie, 5 entrées)
a1 = np.random.randn(5, 4)  # Activation de la couche précédente (5 neurones, 4 exemples)
b2 = np.random.randn(1, 4)  # Biais (1 neurone de sortie, 4 exemples)

# Calcul du pré-activation z2
z2 = np.dot(W2, a1) + b2

# Application de la fonction d'activation
a2 = sigmoid(z2)

# Affichage du résultat final
print("Résultat après activation (a2) :")
print(a2)



Résultat après activation (a2) :
[[0.81246225 0.4662743  0.13948675 0.97797977]]
